all:
  children:
    dev:
      hosts:
        dev_server:
          ansible_host: ec2-16-170-252-85.eu-north-1.compute.amazonaws.com
          ansible_connection: winrm
          ansible_port: 5986
          ansible_user: Administrator
          ansible_password: "{{ host_password }}"
          ansible_winrm_transport: ntlm
          ansible_winrm_scheme: https
          ansible_winrm_server_cert_validation: ignore
    test:
      hosts:
        test_server:
          ansible_host: 194.22.26.240
          ansible_connection: winrm
          ansible_port: 5986
          ansible_user: Administrator
          ansible_password: "{{ host_password }}"
          ansible_winrm_transport: ntlm
          ansible_winrm_scheme: https
          ansible_winrm_server_cert_validation: ignore
